services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=jirka.pinkas@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
  hc1:
    image: hazelcast/hazelcast
    environment:
      - MANCENTER_URL="http://management_center:8080/hazelcast-mancenter
    ports:
      - 5701:5701
  hc2:
    image: hazelcast/hazelcast
    environment:
      - MANCENTER_URL="http://management_center:8080/hazelcast-mancenter
#    ports:
#      - 5702:5701
  management_center:
    image: hazelcast/management-center
    ports:
      - 9090:8080
  app:
    image: demo-hazelcast-2nd-level-cache:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
